### ISSUE TITLE
Add to packagist?

### ISSUE THREAD

**Issue by kynx** [zordius/HandlebarsTest#6]
These are a pretty useful set of test fixtures! Would you consider adding a composer.json and adding to packagist? That would make adding this as a "require-dev" much easier. 

Thanks!

**Comment by zordius** [comment]
Ok, but this is neither a lib or a command line tool, I need some time to figure out best composer.json setting, thanks.

**Comment by zordius** [comment]
Here are some todos:

1. http://stackoverflow.com/questions/18100420/how-do-i-use-a-git-submodule-with-a-composer-loaded-library  composer do not support git submodule, so I need to move git submodules to composer dependency.

2. All required lib should be composer installed including LightnCandy, Handlebars.php, Mustache.php and Mustache-php.

3. Need to update Travis CI build script for these changes.

**Comment by kynx** [comment]
Let me know if there's anything I can do - though maybe a devel branch would be a good idea for this...

**Comment by zordius** [comment]
Or you only need these fixture files? Then I do not need to change handle whole original project testing things, and just create a composer.json for these fixture files.

**Comment by kynx** [comment]
Yes, it's the fixture files I'm after mostly... though the rest is of interest!

FYI I'm also looking at converting the handlebars mocha tests to PHP... not 100% sure how I can automate that yet, but will contribute back if I manage it.

**Comment by zordius** [comment]
I just reviewed composer document again and I think it is not good to serve fixture files with composer:

* composer is designed to handle PHP library dependency, so the major things are PHP and library.
* The project name can not be uppercase, so I will need to change the project name.

So I suggest you to use git submodule to fetch fixture files.

**Comment by zordius** [comment]
If you like to know more handlebars spec for PHP, you can try these:

https://github.com/kasperisager/handlebars-spec
https://github.com/jbboehr/handlebars-spec

**Comment by kynx** [comment]
Many thanks for the links - that'll keep me busy :)
